### ISSUE TITLE
justfile's `gate anti-gaming` / `gates` / `preflight` broke after #594's check-anti-gaming.mjs -> check-verification-erosion.mjs rename

### ISSUE THREAD

**Issue by tsouza-in-automode** [allodops/castle#596]
## What's broken

PR #594 (\`refactor(ci): rename check-anti-gaming.mjs to check-verification-erosion.mjs\`) renamed the script but did not update \`justfile\`'s \`gate name:\` recipe usage. \`justfile\`'s \`gates\` target still calls:

\`\`\`
just gate anti-gaming
\`\`\`

which expands (per the \`gate name:\` recipe) to \`node .github/scripts/check-{{name}}.mjs\`, i.e. \`check-anti-gaming.mjs\` — a file that no longer exists on \`main\`.

Reproduction on current \`main\`:

\`\`\`
$ just gate anti-gaming
node .github/scripts/check-anti-gaming.mjs --self-test
node:internal/modules/cjs/loader:1424
  throw err;
  ^
Error: Cannot find module '.../.github/scripts/check-anti-gaming.mjs'
...
error: Recipe `gate` failed on line 155 with exit code 1
\`\`\`

This breaks:
- \`just gates\` (aborts on the \`anti-gaming\` step, so \`statelessness\`, \`tracing-prefix\`, and \`instrumentation-coverage\` never run locally)
- \`just preflight\` (which calls \`gates\`), i.e. CONTRIBUTING.md's documented "what a contributor runs before pushing" no longer works as-is

The individual gate scripts themselves are fine — \`node .github/scripts/check-verification-erosion.mjs --self-test\` and \`node .github/scripts/check-verification-erosion.mjs origin/main\` both pass clean. This is purely a stale \`justfile\` alias left behind by the rename.

## Fix

Rename the \`just gate\` alias for this check from \`anti-gaming\` to \`verification-erosion\` (or add an explicit override in the \`gate\` recipe / a new recipe, if the shorter alias name is meant to be kept for muscle memory) in \`justfile\`'s \`gates\` target, matching whatever alias \`.github/workflows/anti-gaming-scan.yml\` documents its job id staying as (that workflow's job id was deliberately NOT renamed alongside the script, per its own comment) — decide independently whether the \`just\` alias should track the script name or the job name, and update the one line in \`justfile\` accordingly.

Found while verifying a coincidentally-in-flight, unrelated PR (ratchet-signoff removal) that also runs \`just gates\` as part of its own pre-push checklist.
